openapi: 3.1.0
info:
  title: EpsonConnectAPI
  version: '1.0'
  contact:
    email: foo@example.com
    name: 'Foo '
  description: ''
  summary: Epson Connect API （以降はAPIと記述）は、Epson Connectとつながっているデバイスに対して、外部から印刷等を制御・実行する手段を提供します。
servers:
  - url: 'http://xxxx'
paths:
  /api/1/printing/oauth2/token:
    post:
      summary: 認証
      operationId: post-printing-oauth2-token
      responses:
        '200':
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    token_type: Bearer
                    access_token: meJFiYNJHeH2D4rPLqqvkcr3BrUq4qhcYDkMPxd0y5Xms172iyPHLiAPcrw8vGMk
                    expires_in: 3600
                    refresh_token: 3vBbccxGKf2FAlWLwu8xWnjTNEImJQV6NTdSTCxl0cp91UXpysT1de0syQVgfafk
                    subject_type: ''
                    subject_id: da472a80320345b08761200bb8d9a72a
                properties:
                  token_type:
                    type: string
                    minLength: 1
                    description: “Bearer”固定
                  access_token:
                    type: string
                    minLength: 1
                    description: アクセストークン
                  expires_in:
                    type: number
                    description: |-
                      発行したアクセストークンの有効期限（秒）
                      “3600”（1時間）固定
                  refresh_token:
                    type: string
                    minLength: 1
                    description: |-
                      リフレッシュトークン
                      リフレッシュトークンは認証毎に新しく発行されて、新しく発行された順に5個まで利用可能
                  subject_type:
                    type: string
                    description: 不使用
                  subject_id:
                    type: string
                    minLength: 1
                    description: デバイスを識別するデバイスID
                required:
                  - token_type
                  - access_token
                  - expires_in
                  - refresh_token
                  - subject_type
                  - subject_id
              examples:
                example-1:
                  value:
                    token_type: Bearer
                    access_token: meJFiYNJHeH2D4rPLqqvkcr3BrUq4qhcYDkMPxd0y5Xms172iyPHLiAPcrw8vGMk
                    expires_in: 3600
                    refresh_token: 3vBbccxGKf2FAlWLwu8xWnjTNEImJQV6NTdSTCxl0cp91UXpysT1de0syQVgfafk
                    subject_type: ''
                    subject_id: da472a80320345b08761200bb8d9a72a
        '400':
          description: invalid_request
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            WWW-Authenticate:
              schema:
                type: string
              description: Basic realm="Token Generation" ※ステータスコード401 invalid client返却時のみ
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: invalide client
              examples:
                username、passwordの形式が不正:
                  value:
                    error: invalid_request
                プリンターメールアドレスが不正、もしくはリモートプリント設定で、リモートプリントが不許可:
                  value:
                    error: invalid_grant
                grant_typeが不正:
                  value:
                    error: unsupported_grant_type
        '401':
          description: invalid_client
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            WWW-Authenticate:
              schema:
                type: string
              description: Basic realm="Token Generation" <br>※ステータスコード401 invalid client返却時のみ
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: invalid_client
              examples:
                認証に失敗:
                  value:
                    error: invalid_client
        '500':
          description: server_error
          headers:
            Content-Type:
              schema:
                type: string
              description: application/json; charset=utf-8
            WWW-Authenticate:
              schema:
                type: string
              description: Basic realm="Token Generation" <br>※ステータスコード401 invalid client返却時のみ
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
                x-examples:
                  example-1:
                    error: server_error
              examples:
                予期しないエラー:
                  value:
                    error: server_error
      parameters:
        - schema:
            type: string
          in: query
          name: subject
          description: printer(固定文字列)を指定する
          required: true
        - schema:
            type: string
          in: header
          name: Authorization
          description: クライアントID※とクライアントシークレット※をBasic認証形式でエンコードしたもの ※ライセンス発行時に譲渡
          required: true
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/x-www-form-urlencoded; charset=utf-8
          required: true
      description: APIの利用許可を確認して、デバイスID、アクセストークン、リフレッシュトークンを発行します。
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties: {}
        description: |-
          grant_type=password&username=<プリンタのE-MailAddress>&password=

          ※passwordは空文字を指定する
    parameters: []
  '/api/1/printing/printers/{device_id}/capability/{print_mode}':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
      - schema:
          type: string
        name: print_mode
        in: path
        required: true
    get:
      summary: デバイス印刷能力取得
      tags: []
      responses: {}
      operationId: get-printing-printers-device_id-capability-print_mode
  '/api/1/printing/printers/{device_id}/jobs':
    post:
      summary: 印刷設定
      operationId: post-printing-printers-device_id-jobs
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
  Upload_URL:
    post:
      summary: 印刷ファイルアップロード
      operationId: post-printing-upload-file
      responses:
        '200':
          description: OK
    parameters: []
  '/api/1/printing/printers/{device_id}/jobs/{job_id}/print':
    post:
      summary: 印刷実行
      operationId: post-printing-printers-device_id-jobs-job_id-print
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
      - schema:
          type: string
        name: job_id
        in: path
        required: true
  '/api/1/printing/printers/{device_id}/jobs/{job_id}/cancel':
    post:
      summary: 印刷キャンセル
      operationId: post-printing-printer-device_id-jobs-job_id-cancel
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
      - schema:
          type: string
        name: job_id
        in: path
        required: true
  '/api/1/printing/printers/{device_id}/jobs/{job_id}':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
      - schema:
          type: string
        name: job_id
        in: path
        required: true
    get:
      summary: 印刷ジョブ情報取得
      tags: []
      responses: {}
      operationId: get-printing-printers-device_id-jobs-job_id
  '/api/1/printing/printers/{device_id}':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
    get:
      summary: デバイス情報取得
      tags: []
      responses: {}
      operationId: get-printing-printers-device_id
    delete:
      summary: 認証取り消し
      operationId: delete-printing-device_id
      responses:
        '200':
          description: OK
  '/api/1/printing/printers/{device_id}/settings/notification':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
    post:
      summary: 通知設定
      operationId: post-printing-printers-device_id-settings-notification
      responses:
        '200':
          description: OK
      description: ''
  '/api/1/scanning/scanners/{device_id}/destinations':
    parameters:
      - schema:
          type: string
        name: device_id
        in: path
        required: true
    post:
      summary: スキャン宛先一覧取得
      operationId: post-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
    get:
      summary: ''
      operationId: get-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
    put:
      summary: ''
      operationId: put-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-scanning-scanners-device_id-destinations
      responses:
        '200':
          description: OK
components:
  schemas: {}
